/* Neuroanatomia — wspólne dane pojęć dla ściągi i narzędzia active recall.
   Kolejność DOKŁADNIE jak w POMOCNIKU (część I, potem II, potem III/IV).
   Pola: p=część, t=pojęcie, l=łac., co/gd/zc/pc = co/gdzie/z czego/po co (puste pomijane). */
const NEURO_CONCEPTS = [
// ===== CZĘŚĆ I — POJĘCIA ANATOMICZNE =====
{p:"I",t:"pokrywa",l:"tectum",co:"grzbietowa część śródmózgowia",gd:"ku tyłowi od wodociągu",zc:"blaszka czworacza (4 wzgórki)",pc:"ośrodki odruchów wzrokowych i słuchowych"},
{p:"I",t:"blaszka czworacza (blaszka pokrywy)",l:"lamina tecti",co:"płytka pokrywy śródmózgowia",gd:"tylna powierzchnia śródmózgowia",zc:"2 wzgórki górne i 2 dolne",pc:"podkorowe ośrodki wzroku (górne) i słuchu (dolne)"},
{p:"I",t:"droga czworaczo-rdzeniowa = pokrywowo-rdzeniowa",l:"tractus tectospinalis",co:"droga pozapiramidowa zstępująca",gd:"z pokrywy do rdzenia",zc:"włókna z wzgórków pokrywy",pc:"odruchowe ruchy głowy/tułowia na bodźce wzrokowe i słuchowe"},
{p:"I",t:"ciała suteczkowate",l:"corpora mamillaria",co:"parzyste wyniosłości istoty szarej",gd:"dolna powierzchnia podwzgórza",zc:"jądra suteczkowate",pc:"układ limbiczny (krąg Papeza, pamięć); odbierają sklepienie"},
{p:"I",t:"ciało kolankowate boczne",l:"corpus geniculatum laterale",co:"jądro zawzgórza",gd:"tylno-dolna część wzgórza",pc:"podkorowy ośrodek wzroku (pasmo wzrokowe → kora wzrokowa)"},
{p:"I",t:"ciało migdałowate",l:"corpus amygdaloideum",co:"jądro podstawne",gd:"biegun skroniowy, przy ogonie jądra ogoniastego",zc:"skupisko jąder",pc:"układ limbiczny — emocje (lęk, agresja)"},
{p:"I",t:"ciało modzelowate (spoidło wielkie mózgu)",l:"corpus callosum",co:"największe spoidło mózgu",gd:"dno szczeliny podłużnej, łączy półkule",zc:"włókna spoidłowe (komisuralne)",pc:"łączy korę obu półkul"},
{p:"I",t:"ciało prążkowane (prążkowie)",l:"corpus striatum",co:"zespół jąder podstawnych",gd:"w głębi półkul",zc:"jądro ogoniaste + soczewkowate (neostriatum = ogoniaste+skorupa; paleostriatum = gałka blada)",pc:"układ pozapiramidowy (kontrola ruchu, napięcie mięśni)"},
{p:"I",t:"dół równoległoboczny",l:"fossa rhomboidea",co:"dno komory IV",gd:"tylna powierzchnia mostu i opuszki",pc:"rzutują się na nim jądra nerwów czaszkowych"},
{p:"I",t:"droga czerwienno-rdzeniowa",l:"tractus rubrospinalis",co:"droga pozapiramidowa",gd:"z jądra czerwiennego (krzyżuje się) → sznur boczny",zc:"aksony jądra czerwiennego",pc:"napięcie zginaczy, współpraca z móżdżkiem"},
{p:"I",t:"droga korowo-jądrowa",l:"tractus corticonuclearis",co:"droga piramidowa",gd:"kora ruchowa → kolanko torebki wewnętrznej → jądra ruchowe nn. czaszkowych",zc:"aksony komórek kory ruchowej",pc:"ruchy dowolne mięśni głowy i szyi"},
{p:"I",t:"droga korowo-rdzeniowa boczna",l:"tractus corticospinalis lateralis",co:"główna droga piramidowa",gd:"skrzyżowana w piramidach → sznur boczny",zc:"~80–90% włókien korowo-rdzeniowych",pc:"ruchy precyzyjne kończyn (strona przeciwna)"},
{p:"I",t:"droga korowo-rdzeniowa przednia",l:"tractus corticospinalis anterior",co:"droga piramidowa",gd:"nieskrzyżowana w piramidach → sznur przedni",zc:"~10–20% włókien (krzyżują się na poziomie segmentu)",pc:"mięśnie tułowia"},
{p:"I",t:"droga oliwkowo-rdzeniowa",l:"tractus olivospinalis",co:"droga pozapiramidowa",gd:"z jądra oliwki → rdzeń",zc:"aksony jądra oliwki",pc:"koordynacja, modulacja napięcia mięśni"},
{p:"I",t:"droga piramidowa",l:"tractus pyramidalis",co:"droga ruchów dowolnych",gd:"kora ruchowa → piramidy → rdzeń / jądra nn. czaszkowych",zc:"2 neurony główne (ośrodkowy i obwodowy)",pc:"ruchy dowolne"},
{p:"I",t:"droga pozapiramidowa",co:"zespół dróg zstępujących poza piramidową",gd:"z jąder podkorowych i pnia → rdzeń",zc:"czerwienno-, przedsionkowo-, siatkowo-, pokrywowo-, oliwkowo-rdzeniowa",pc:"napięcie mięśni, postawa, ruchy automatyczne"},
{p:"I",t:"droga przedsionkowo-rdzeniowa",l:"tractus vestibulospinalis",co:"droga pozapiramidowa",gd:"z jąder przedsionkowych → sznur przedni",zc:"aksony jąder przedsionkowych",pc:"postawa, równowaga, napięcie prostowników"},
{p:"I",t:"droga rdzeniowo-wzgórzowa boczna",l:"tractus spinothalamicus lateralis",co:"droga czuciowa wstępująca",gd:"róg tylny → krzyżuje w rdzeniu → sznur boczny → VPL",zc:"3 neurony (zwój, jądro własne rogu tylnego, wzgórze)",pc:"ból i temperatura (czucie protopatyczne)"},
{p:"I",t:"droga rdzeniowo-wzgórzowa przednia",l:"tractus spinothalamicus anterior",co:"droga czuciowa wstępująca",gd:"róg tylny → krzyżuje → sznur przedni → VPL",zc:"3 neurony",pc:"dotyk gruby i ucisk (protopatyczne)"},
{p:"I",t:"droga rdzeniowo-móżdżkowa przednia (Gowersa)",l:"tractus spinocerebellaris anterior",co:"droga domóżdżkowa (czucie głębokie nieświadome)",gd:"sznur boczny → konar górny móżdżku",zc:"podwójnie skrzyżowana",pc:"bieżąca kontrola ruchu przez móżdżek"},
{p:"I",t:"droga rdzeniowo-móżdżkowa tylna (Flechsiga)",l:"tractus spinocerebellaris posterior",co:"droga domóżdżkowa",gd:"z jądra Clarke'a → sznur boczny → konar dolny",zc:"nieskrzyżowana",pc:"czucie głębokie nieświadome z dolnej połowy ciała"},
{p:"I",t:"droga rdzeniowo-opuszkowa",co:"czuciowa (sznury tylne biegnące do opuszki)",gd:"pęczki smukły/klinowaty → jądra smukłe/klinowate",zc:"włókna I neuronu z zwoju rdzeniowego",pc:"czucie epikrytyczne i głębokie świadome (dalej wstęga przyśrodkowa)"},
{p:"I",t:"droga siatkowo-rdzeniowa",l:"tractus reticulospinalis",co:"droga pozapiramidowa",gd:"z tworu siatkowatego mostu i opuszki → rdzeń",zc:"aksony tworu siatkowatego",pc:"napięcie mięśni, ruchy automatyczne, modulacja odruchów"},
{p:"I",t:"gałka blada",l:"globus pallidus",co:"część jądra soczewkowatego (paleostriatum)",gd:"przyśrodkowa część jądra soczewkowatego",pc:"główne jądro wyjściowe prążkowia (pozapiramidowy)"},
{p:"I",t:"guz popielaty",l:"tuber cinereum",co:"wyniosłość istoty szarej",gd:"podwzgórze, ku przodowi od ciał suteczkowatych",zc:"przechodzi w lejek",pc:"kontrola przysadki"},
{p:"I",t:"hipokamp",l:"hippocampus",co:"zawinięta kora płata skroniowego",gd:"dno rogu dolnego komory bocznej",zc:"kora najstarsza (archikora)",pc:"pamięć (układ limbiczny); odprowadza sklepienie"},
{p:"I",t:"istota czarna",l:"substantia nigra",co:"jądro śródmózgowia",gd:"między odnogą a nakrywką konaru",zc:"neurony z melaniną (dopamina)",pc:"ośrodek pozapiramidowy (napięcie mięśni; uszkodzenie → parkinsonizm)"},
{p:"I",t:"istota galaretowata (Rolanda)",l:"substantia gelatinosa",co:"jądro czuciowe rdzenia",gd:"szczyt rogu tylnego",pc:"modulacja bólu i temperatury (bramka bólowa)"},
{p:"I",t:"jądra przedsionkowe",co:"jądra czuciowe nerwu VIII",gd:"dno komory IV (pole przedsionkowe)",pc:"równowaga; początek drogi przedsionkowo-rdzeniowej"},
{p:"I",t:"jądra ślimakowe",co:"jądra czuciowe nerwu VIII",gd:"okolica konara dolnego / dna komory IV",pc:"słuch; początek drogi słuchowej → wstęga boczna"},
{p:"I",t:"jądro czerwienne",l:"nucleus ruber",co:"jądro nakrywki śródmózgowia",gd:"nakrywka śródmózgowia",pc:"ośrodek pozapiramidowy; początek drogi czerwienno-rdzeniowej"},
{p:"I",t:"jądro czopowate",l:"nucleus emboliformis",co:"jądro móżdżku",gd:"istota biała móżdżku (obok kulkowatego)",pc:"staromóżdżek (napięcie mięśni)"},
{p:"I",t:"jądro dodatkowe n. III (Westphala-Edingera)",co:"jądro przywspółczulne",gd:"śródmózgowie",pc:"zwężenie źrenicy i akomodacja"},
{p:"I",t:"jądro dwuznaczne",l:"nucleus ambiguus",co:"jądro ruchowe skrzelopochodne",gd:"rdzeń przedłużony",pc:"mięśnie gardła i krtani (nn. IX, X, część XI)"},
{p:"I",t:"jądro klinowate",l:"nucleus cuneatus",co:"jądro czuciowe (II neuron)",gd:"opuszka, pod guzkiem klinowatym",pc:"kończy pęczek klinowaty (czucie z górnej połowy ciała) → wstęga przyśrodkowa"},
{p:"I",t:"jądro przywspółczulne krzyżowe",co:"jądro autonomiczne",gd:"róg boczny S2–S4",zc:"neurony przedzwojowe",pc:"narządy miednicy (pęcherz, jelito, narządy płciowe)"},
{p:"I",t:"jądro kulkowate",l:"nucleus globosus",co:"jądro móżdżku",gd:"istota biała móżdżku",pc:"staromóżdżek (z czopowatym = jądro wtrącone)"},
{p:"I",t:"jądro ogoniaste",l:"nucleus caudatus",co:"jądro podstawne",gd:"wzdłuż komory bocznej (głowa, trzon, ogon)",zc:"istota szara (neostriatum)",pc:"układ pozapiramidowy"},
{p:"I",t:"jądro oliwki",l:"nucleus olivaris",co:"jądro pozapiramidowe",gd:"w oliwce opuszki",zc:"pofałdowane jądro",pc:"koordynacja ruchu; połączenia z móżdżkiem (droga oliwkowo-rdzeniowa)"},
{p:"I",t:"jądro główne n. V",co:"jądro czuciowe nerwu V",gd:"most",pc:"czucie dotyku z twarzy (epikrytyczne)"},
{p:"I",t:"jądro pasma rdzeniowego n. V",co:"jądro czuciowe nerwu V",gd:"opuszka i rdzeń szyjny",pc:"ból i temperatura z twarzy (protopatyczne)"},
{p:"I",t:"jądro pasma śródmózgowiowego n. V",co:"jądro czuciowe nerwu V (wyjątkowe)",gd:"śródmózgowie",zc:"ciała I neuronu czuciowego w OUN",pc:"czucie proprioceptywne z mięśni żucia"},
{p:"I",t:"jądro piersiowe (Clarke'a)",co:"jądro czuciowe rdzenia",gd:"podstawa rogu tylnego, C8–L2/3",pc:"początek drogi rdzeniowo-móżdżkowej tylnej"},
{p:"I",t:"jądro pośrednio-boczne",co:"jądro autonomiczne",gd:"róg boczny Th1–L2/3",zc:"neurony przedzwojowe",pc:"ośrodek współczulny"},
{p:"I",t:"jądro pośrednio-przyśrodkowe",co:"jądro czuciowe trzewne",gd:"istota pośrednia rdzenia",pc:"czucie trzewne; łączność z autonomiką"},
{p:"I",t:"jądro brzuszne tylno-boczne (VPL)",co:"jądro wzgórza",gd:"brzuszno-tylna część wzgórza",zc:"III neuron drogi czuciowej",pc:"czucie z tułowia i kończyn → kora czuciowa"},
{p:"I",t:"jądro brzuszne tylno-przyśrodkowe (VPM)",co:"jądro wzgórza",gd:"brzuszno-tylna część wzgórza",zc:"III neuron",pc:"czucie z głowy (wstęga trójdzielna) i smak → kora"},
{p:"I",t:"jądro ruchowe n. III",co:"jądro ruchowe somatyczne",gd:"śródmózgowie (wysokość wzgórków górnych)",pc:"mięśnie gałki ocznej i dźwigacz powieki (n. okoruchowy)"},
{p:"I",t:"jądro ruchowe n. IV",co:"jądro ruchowe somatyczne",gd:"śródmózgowie (wysokość wzgórków dolnych)",pc:"mięsień skośny górny gałki (n. bloczkowy)"},
{p:"I",t:"jądro ruchowe n. IX",co:"jądro ruchowe skrzelopochodne",gd:"opuszka (górna część jądra dwuznacznego)",pc:"mięsień rylcowo-gardłowy"},
{p:"I",t:"jądro ruchowe n. V",co:"jądro ruchowe skrzelopochodne",gd:"most",pc:"mięśnie żucia (n. trójdzielny)"},
{p:"I",t:"jądro ruchowe n. VI",co:"jądro ruchowe somatyczne",gd:"most",pc:"mięsień prosty boczny gałki (n. odwodzący)"},
{p:"I",t:"jądro ruchowe n. VII",co:"jądro ruchowe skrzelopochodne",gd:"most",pc:"mięśnie mimiczne (n. twarzowy)"},
{p:"I",t:"jądro ruchowe n. XI",co:"jądro ruchowe (część rdzeniowa)",gd:"róg przedni rdzenia szyjnego C1–C5/6",pc:"mięsień MOS i czworoboczny"},
{p:"I",t:"jądro ruchowe n. XII",co:"jądro ruchowe somatyczne",gd:"opuszka (trójkąt nerwu podjęzykowego)",pc:"mięśnie języka"},
{p:"I",t:"jądro samotne",l:"nucleus solitarius",co:"jądro czuciowe",gd:"rdzeń przedłużony",pc:"smak i czucie trzewne (nn. VII, IX, X)"},
{p:"I",t:"jądro smukłe",l:"nucleus gracilis",co:"jądro czuciowe (II neuron)",gd:"opuszka, pod guzkiem smukłym",pc:"kończy pęczek smukły (czucie z dolnej połowy ciała) → wstęga przyśrodkowa"},
{p:"I",t:"jądro soczewkowate",l:"nucleus lentiformis",co:"jądro podstawne",gd:"bocznie od wzgórza i torebki wewnętrznej",zc:"skorupa + gałka blada",pc:"układ pozapiramidowy"},
{p:"I",t:"jądro ślinowe dolne",co:"jądro przywspółczulne",gd:"rdzeń przedłużony",pc:"ślinianka przyuszna (n. IX)"},
{p:"I",t:"jądro ślinowe górne",co:"jądro przywspółczulne",gd:"most",pc:"ślinianki podżuchwowa i podjęzykowa, gruczoł łzowy (n. VII)"},
{p:"I",t:"jądro wierzchu",l:"nucleus fastigii",co:"jądro móżdżku",gd:"najbardziej przyśrodkowe (przy robaku)",pc:"równowaga (układ przedsionkowy)"},
{p:"I",t:"jądro własne rogu tylnego",co:"jądro czuciowe rdzenia (II neuron)",gd:"róg tylny",pc:"początek dróg rdzeniowo-wzgórzowych (czucie protopatyczne)"},
{p:"I",t:"jądro zatylno-boczne",co:"jądro kojarzeniowe wzgórza",gd:"tylno-boczna część wzgórza",pc:"integracja czuciowa; łączność z korą ciemieniową"},
{p:"I",t:"jądro zębate",l:"nucleus dentatus",co:"największe jądro móżdżku",gd:"boczna część istoty białej móżdżku",pc:"nowy móżdżek — koordynacja ruchów dowolnych (droga zębato-czerwienna i zębato-wzgórzowa)"},
{p:"I",t:"komora boczna",co:"jama kresomózgowia",gd:"w półkuli",zc:"róg przedni, trzon, róg tylny i dolny",pc:"zawiera płyn m-r (splot naczyniówkowy)"},
{p:"I",t:"komora czwarta",co:"jama tyłomózgowia",gd:"między mostem/opuszką a móżdżkiem",zc:"dno = dół równoległoboczny",pc:"płyn m-r; otwory Magendiego i Luschki"},
{p:"I",t:"komora trzecia",co:"jama międzymózgowia",gd:"między wzgórzami",pc:"płyn m-r; łączy się z IV przez wodociąg"},
{p:"I",t:"konar mózgu (odnoga mózgu)",l:"crus cerebri",co:"przednia część konaru śródmózgowia",gd:"przednia powierzchnia śródmózgowia",zc:"drogi zstępujące (korowo-rdzeniowe, -jądrowe, -mostowe)",pc:"przewodzenie dróg ruchowych w dół"},
{p:"I",t:"konar móżdżku",l:"pedunculus cerebellaris",co:"pasmo łączące móżdżek z pniem",gd:"górny, środkowy, dolny",zc:"włókna do i z móżdżku",pc:"połączenia móżdżku z pniem"},
{p:"I",t:"konar śródmózgowia (= odnoga mózgu + nakrywka)",co:"boczna część śródmózgowia",gd:"po bokach wodociągu",zc:"odnoga mózgu (drogi) + nakrywka (jądra); granica = istota czarna",pc:"przewodzenie dróg i lokalizacja jąder śródmózgowia"},
{p:"I",t:"korzeń przedni nerwu rdzeniowego",co:"korzeń ruchowy",gd:"wychodzi z przednio-bocznej powierzchni rdzenia",zc:"aksony motoneuronów (+ włókna autonomiczne)",pc:"unerwienie ruchowe"},
{p:"I",t:"kora ruchowa",co:"pole ruchowe kory",gd:"zakręt przedśrodkowy",zc:"kora (komórki Betza)",pc:"ruchy dowolne (początek drogi piramidowej)"},
{p:"I",t:"kora czuciowa",co:"pole czuciowe kory",gd:"zakręt zaśrodkowy",pc:"czucie ze skóry i ciała"},
{p:"I",t:"kora wzrokowa",co:"pole wzrokowe kory",gd:"wokół bruzdy ostrogowej (płat potyliczny)",pc:"widzenie"},
{p:"I",t:"kora słuchowa",co:"pole słuchowe kory",gd:"zakręty skroniowe poprzeczne (Heschla)",pc:"słuch"},
{p:"I",t:"kora smakowa",co:"pole smakowe kory",gd:"dolna część zakrętu zaśrodkowego / wyspa",pc:"smak"},
{p:"I",t:"kora somatomotoryczna",co:"= kora ruchowa",gd:"zakręt przedśrodkowy",pc:"ruchy dowolne ciała"},
{p:"I",t:"kora somatosensoryczna",co:"= kora czuciowa",gd:"zakręt zaśrodkowy",pc:"czucie ciała"},
{p:"I",t:"korzeń tylny nerwu rdzeniowego",co:"korzeń czuciowy",gd:"wchodzi do tylno-bocznej powierzchni rdzenia",zc:"włókna neuronów zwoju rdzeniowego (na nim leży zwój)",pc:"czucie"},
{p:"I",t:"międzymózgowie",l:"diencephalon",co:"część mózgowia",gd:"między kresomózgowiem a śródmózgowiem",zc:"wzgórze, zawzgórze, nadwzgórze, podwzgórze",pc:"przekaźnictwo czucia, autonomika i hormony"},
{p:"I",t:"most",l:"pons",co:"środkowa część pnia mózgu",gd:"między opuszką a śródmózgowiem",zc:"część podstawna + nakrywka",pc:"łączy korę z móżdżkiem; jądra nn. V–VIII"},
{p:"I",t:"nakrywka",l:"tegmentum",co:"grzbietowa część konaru/pnia",gd:"do tyłu od istoty czarnej (w śródmózgowiu)",zc:"jądra, twór siatkowaty, drogi wstępujące",pc:"lokalizacja jąder i dróg czuciowych"},
{p:"I",t:"nerw bloczkowy (IV)",l:"n. trochlearis",co:"nerw ruchowy",gd:"jedyny z tylnej powierzchni pnia",zc:"włókna z jądra n. IV",pc:"mięsień skośny górny gałki"},
{p:"I",t:"nerw błędny (X)",l:"n. vagus",co:"nerw mieszany, najdłuższy",gd:"z opuszki",zc:"włókna ruchowe, czuciowe i przywspółczulne",pc:"głównie przywspółczulny narządów klatki piersiowej i brzucha"},
{p:"I",t:"nerw dodatkowy (XI)",l:"n. accessorius",co:"nerw ruchowy",gd:"z opuszki / rdzenia szyjnego",zc:"część rdzeniowa C1–C5",pc:"mięsień MOS i czworoboczny"},
{p:"I",t:"nerw językowo-gardłowy (IX)",l:"n. glossopharyngeus",co:"nerw mieszany",gd:"z opuszki",pc:"gardło, ślinianka przyuszna, smak i czucie z 1/3 tylnej języka"},
{p:"I",t:"nerw odwodzący (VI)",l:"n. abducens",co:"nerw ruchowy",gd:"z mostu",zc:"włókna z jądra n. VI",pc:"mięsień prosty boczny (odwodzi oko)"},
{p:"I",t:"nerw okoruchowy (III)",l:"n. oculomotorius",co:"nerw ruchowy i przywspółczulny",gd:"ze śródmózgowia",pc:"większość mięśni gałki, dźwigacz powieki, źrenica i akomodacja"},
{p:"I",t:"nerw podjęzykowy (XII)",l:"n. hypoglossus",co:"nerw ruchowy",gd:"z opuszki",pc:"mięśnie języka"},
{p:"I",t:"nerw przedsionkowo-ślimakowy (VIII) / statyczno-słuchowy",l:"n. vestibulocochlearis",co:"nerw czuciowy",gd:"kąt mostowo-móżdżkowy",zc:"część przedsionkowa + ślimakowa",pc:"równowaga i słuch"},
{p:"I",t:"nerwy główne wszystkich splotów",co:"główne nerwy splotów",gd:"szyjny→przeponowy; ramienny→pośrodkowy, łokciowy, promieniowy, pachowy, mięśniowo-skórny; lędźwiowy→udowy, zasłonowy; krzyżowy→kulszowy",pc:"unerwienie kończyn i przepony"},
{p:"I",t:"węchomózgowie",l:"rhinencephalon",co:"najstarsza część kresomózgowia",gd:"dolna/przyśrodkowa powierzchnia półkul",zc:"opuszka i pasmo węchowe, kora węchowa",pc:"węch (powiązany z układem limbicznym)"},
{p:"I",t:"nerw rdzeniowy (31 par) / pień nerwu rdzeniowego",co:"nerw mieszany",gd:"z połączenia korzenia przedniego i tylnego",zc:"włókna czuciowe, ruchowe i autonomiczne",pc:"unerwienie tułowia i kończyn"},
{p:"I",t:"nerw trójdzielny (V)",l:"n. trigeminus",co:"nerw mieszany",gd:"z mostu",zc:"3 gałęzie: oczna, szczękowa, żuchwowa",pc:"czucie z twarzy + mięśnie żucia"},
{p:"I",t:"nerw twarzowy (VII)",l:"n. facialis",co:"nerw mieszany",gd:"kąt mostowo-móżdżkowy",pc:"mięśnie mimiczne, łzy i ślinianki, smak z 2/3 przednich języka"},
{p:"I",t:"nerw węchowy (I)",l:"n. olfactorius",co:"nerw czuciowy",gd:"nici z błony śluzowej nosa → opuszka węchowa",pc:"węch"},
{p:"I",t:"nerw wzrokowy (II)",l:"n. opticus",co:"nerw czuciowy (właściwie pasmo OUN)",gd:"z siatkówki → skrzyżowanie wzrokowe",pc:"wzrok"},
{p:"I",t:"nici korzeniowe",l:"fila radicularia",co:"pasemka włókien korzeni",gd:"na powierzchni rdzenia",pc:"łączą się w korzeń"},
{p:"I",t:"nić końcowa",l:"filum terminale",co:"pasmo (głównie opony miękkiej)",gd:"od stożka do kości guzicznej",pc:"mocuje rdzeń"},
{p:"I",t:"nowy móżdżek",l:"neocerebellum",co:"filogenetycznie najmłodsza część móżdżku",gd:"boczne części półkul",pc:"koordynacja ruchów dowolnych"},
{p:"I",t:"ogon koński",l:"cauda equina",co:"pęczek korzeni nerwów",gd:"poniżej stożka (L1/L2)",pc:"unerwienie odcinka L, S, Co"},
{p:"I",t:"oliwka",l:"oliva",co:"wyniesienie opuszki",gd:"bocznie od piramidy",zc:"jądro oliwki",pc:"koordynacja (układ pozapiramidowy)"},
{p:"I",t:"opuszka rdzeniowa (rdzeń przedłużony)",l:"medulla oblongata",co:"najniższa część pnia mózgu",gd:"między rdzeniem a mostem",zc:"piramidy, oliwki, jądra nn. i smukłe/klinowate",pc:"ośrodki życiowe, drogi, jądra nerwów"},
{p:"I",t:"opuszka węchowa",l:"bulbus olfactorius",co:"uwypuklenie pasma węchowego",gd:"na blaszce sitowej",zc:"II neuron drogi węchowej",pc:"kończą się nici węchowe, zaczyna pasmo węchowe"},
{p:"I",t:"ośrodek naczynioruchowy",co:"ośrodek autonomiczny",gd:"twór siatkowaty opuszki",pc:"napięcie naczyń i ciśnienie krwi"},
{p:"I",t:"ośrodek potowydzielniczy",co:"ośrodek współczulny",gd:"rogi boczne rdzenia / podwzgórze",pc:"wydzielanie potu"},
{p:"I",t:"pasmo węchowe",l:"tractus olfactorius",co:"droga węchowa",gd:"od opuszki do kory węchowej",pc:"przewodzi węch (z pominięciem wzgórza)"},
{p:"I",t:"pęczek klinowaty (Burdacha)",l:"fasciculus cuneatus",co:"pęczek sznura tylnego",gd:"boczny, od Th6 w górę",zc:"włókna I neuronu czuciowego",pc:"czucie epikrytyczne/głębokie z górnej połowy ciała"},
{p:"I",t:"pęczek międzypęczkowy",co:"część pęczków własnych rdzenia",gd:"sznur tylny",pc:"zstępujące włókna śródrdzeniowe"},
{p:"I",t:"pęczek przegrodowo-brzeżny",co:"część pęczków własnych rdzenia",gd:"sznur tylny",pc:"własne (śródrdzeniowe) włókna zstępujące"},
{p:"I",t:"pęczek smukły (Golla)",l:"fasciculus gracilis",co:"pęczek sznura tylnego",gd:"przyśrodkowy",zc:"włókna I neuronu czuciowego",pc:"czucie epikrytyczne/głębokie z dolnej połowy ciała"},
{p:"I",t:"pęczek własny rdzenia kręgowego",l:"fasciculi proprii",co:"drogi własne rdzenia",gd:"warstwa wokół istoty szarej",pc:"łączą segmenty (odruchy wielosegmentowe)"},
{p:"I",t:"pień mózgu",l:"truncus encephali",co:"rdzeń przedłużony + most + śródmózgowie",gd:"podstawa mózgowia",zc:"jądra nn. czaszkowych, twór siatkowaty, drogi",pc:"ośrodki życiowe i przewodzenie"},
{p:"I",t:"piramida",l:"pyramis",co:"wał na przedniej powierzchni opuszki",gd:"opuszka, przyśrodkowo",zc:"włókna korowo-rdzeniowe",pc:"ruch dowolny"},
{p:"I",t:"płacik okołośrodkowy (część przednia i tylna)",l:"lobulus paracentralis",co:"pole na powierzchni przyśrodkowej półkuli",gd:"przedłużenie zakrętów środkowych",zc:"część przednia (ruchowa) + tylna (czuciowa)",pc:"ruch i czucie kończyny dolnej i krocza; kontrola zwieraczy"},
{p:"I",t:"płaszcz",l:"pallium",co:"kora wraz z podkorową istotą białą",gd:"pokrywa półkule",pc:"czynności wyższe (kora)"},
{p:"I",t:"podwzgórze",l:"hypothalamus",co:"dolna część międzymózgowia",gd:"dno i dolne ściany komory III",zc:"jądra podwzgórza",pc:"nadrzędny ośrodek autonomiczny i hormonalny"},
{p:"I",t:"pole korzeniowe",co:"strefa wnikania nici korzeniowych",gd:"przednio-boczna i tylno-boczna powierzchnia rdzenia",pc:"wejście/wyjście korzeni"},
{p:"I",t:"pozorne wstępowanie rdzenia kręgowego",co:"zjawisko rozwojowe",gd:"rdzeń krótszy niż kanał kręgowy",pc:"tłumaczy skośny przebieg korzeni i ogon koński"},
{p:"I",t:"pramóżdżek",l:"archicerebellum",co:"najstarsza część móżdżku",gd:"płat grudkowo-kłaczkowy",pc:"równowaga (układ przedsionkowy)"},
{p:"I",t:"przedmurze",l:"claustrum",co:"blaszka istoty szarej",gd:"między skorupą a korą wyspy",pc:"funkcja niejasna (powiązania z korą)"},
{p:"I",t:"rdzeniomózgowie",l:"myelencephalon",co:"pęcherzyk mózgowy wtórny",pc:"daje rdzeń przedłużony"},
{p:"I",t:"robak móżdżku",l:"vermis",co:"środkowa część móżdżku",gd:"między półkulami",pc:"oś ciała, postawa, napięcie mięśni"},
{p:"I",t:"róg (słup) rdzeniowy",co:"wypustki istoty szarej rdzenia",gd:"tylny (czuciowy), przedni (ruchowy), boczny (autonomiczny)",pc:"odbiór i wysyłanie impulsów"},
{p:"I",t:"sklepienie (fornix)",l:"fornix",co:"łukowate pasmo istoty białej",gd:"od hipokampa do ciał suteczkowatych",pc:"główna droga odprowadzająca hipokampa (limbiczny)"},
{p:"I",t:"sierp mózgu",l:"falx cerebri",co:"wypustka opony twardej",gd:"szczelina podłużna między półkulami",pc:"oddziela półkule"},
{p:"I",t:"sierp móżdżku",l:"falx cerebelli",co:"wypustka opony twardej",gd:"między półkulami móżdżku",pc:"oddziela półkule móżdżku"},
{p:"I",t:"przepona siodła tureckiego",l:"diaphragma sellae",co:"blaszka opony twardej",gd:"nad siodłem tureckim",pc:"przykrywa przysadkę (przepuszcza lejek)"},
{p:"I",t:"przestrzeń podpajęczynówkowa",co:"przestrzeń między oponami",gd:"między pajęczą a miękką",zc:"wypełniona płynem m-r",pc:"krążenie płynu, amortyzacja"},
{p:"I",t:"opona twarda",l:"dura mater",co:"najbardziej zewnętrzna opona",gd:"pod kością",zc:"gruba, włóknista",pc:"ochrona; tworzy wypustki i zatoki żylne"},
{p:"I",t:"opona miękka",l:"pia mater",co:"najgłębsza opona",gd:"przylega do powierzchni mózgu/rdzenia",pc:"odżywianie (bogato unaczyniona)"},
{p:"I",t:"opona pajęcza (pajęczynówka)",l:"arachnoidea",co:"środkowa opona",gd:"między twardą a miękką",pc:"pod nią płyn m-r"},
{p:"I",t:"namiot móżdżku",l:"tentorium cerebelli",co:"wypustka opony twardej",gd:"między móżdżkiem a płatami potylicznymi",pc:"oddziela móżdżek od mózgu"},
{p:"I",t:"skorupa",l:"putamen",co:"część jądra soczewkowatego",gd:"boczna (z jądrem ogoniastym = neostriatum)",pc:"układ pozapiramidowy"},
{p:"I",t:"skrzyżowanie piramid",l:"decussatio pyramidum",co:"skrzyżowanie włókien ruchowych",gd:"granica opuszki i rdzenia",pc:"~80–90% włókien korowo-rdzeniowych przechodzi na stronę przeciwną"},
{p:"I",t:"skrzyżowanie wstęg",l:"decussatio lemniscorum",co:"skrzyżowanie włókien czuciowych",gd:"opuszka",pc:"aksony jąder smukłego/klinowatego → wstęga przyśrodkowa"},
{p:"I",t:"skrzyżowanie wzrokowe",l:"chiasma opticum",co:"skrzyżowanie włókien wzrokowych",gd:"na podstawie mózgu, przed lejkiem",pc:"częściowe skrzyżowanie (włókna z nosowych połów siatkówek)"},
{p:"I",t:"stary móżdżek",l:"paleocerebellum",co:"filogenetyczna część móżdżku",gd:"robak i przyśrodkowe części półkul",pc:"czucie głębokie (postawa, napięcie mięśni)"},
{p:"I",t:"sznur rdzeniowy (przedni, boczny, tylny)",l:"funiculus",co:"część istoty białej rdzenia",gd:"podzielona rogami na 3 sznury",zc:"drogi wstępujące i zstępujące",pc:"przewodzenie impulsów"},
{p:"I",t:"śródmózgowie",l:"mesencephalon",co:"najkrótsza część pnia mózgu",gd:"między mostem a międzymózgowiem",zc:"pokrywa + konary; jama = wodociąg",pc:"odruchy wzrokowo-słuchowe, ośrodki pozapiramidowe"},
{p:"I",t:"torebka wewnętrzna (odnoga przednia, kolanko, tylna)",l:"capsula interna",co:"warstwa istoty białej",gd:"między jądrem soczewkowatym a wzgórzem/ogoniastym",zc:"odnoga przednia, kolanko, odnoga tylna",pc:"drogi rzutowe (ruchowe i czuciowe)"},
{p:"I",t:"twór siatkowaty",l:"formatio reticularis",co:"sieć rozproszonych neuronów pnia",gd:"nakrywka pnia mózgu",pc:"czuwanie (ARAS), ośrodki życiowe, napięcie mięśni"},
{p:"I",t:"tyłomózgowie wtórne",l:"metencephalon",co:"pęcherzyk mózgowy wtórny",pc:"daje most i móżdżek"},
{p:"I",t:"układ brzeżny (limbiczny, rąbkowy)",l:"systema limbicum",co:"zespół struktur",gd:"przyśrodkowa powierzchnia półkul",zc:"hipokamp, ciało migdałowate, sklepienie, ciała suteczkowate, zakręt obręczy",pc:"emocje, pamięć, popędy"},
{p:"I",t:"wieniec promienisty",l:"corona radiata",co:"wachlarz włókien rzutowych",gd:"między torebką wewnętrzną a korą",pc:"łączy korę z drogami rzutowymi"},
{p:"I",t:"wodociąg mózgu",l:"aqueductus cerebri",co:"kanał śródmózgowia",gd:"między komorą III a IV",pc:"przepływ płynu m-r"},
{p:"I",t:"wstęga przyśrodkowa",l:"lemniscus medialis",co:"pasmo czuciowe (II neuron)",gd:"pień mózgu → VPL",zc:"z jąder smukłego/klinowatego",pc:"czucie epikrytyczne i głębokie"},
{p:"I",t:"wstęga rdzeniowa",l:"lemniscus spinalis",co:"pasmo czuciowe",gd:"pień mózgu → VPL",zc:"drogi rdzeniowo-wzgórzowe",pc:"czucie protopatyczne"},
{p:"I",t:"wstęga boczna",l:"lemniscus lateralis",co:"pasmo słuchowe",gd:"pień → wzgórki dolne i ciało kolankowate przyśrodkowe",zc:"z jąder ślimakowych",pc:"słuch"},
{p:"I",t:"wstęga trójdzielna",co:"pasmo czuciowe",gd:"pień mózgu → VPM",zc:"z jąder czuciowych nerwu V",pc:"czucie z głowy"},
{p:"I",t:"wzgórki górne pokrywy",co:"część blaszki czworaczej",gd:"śródmózgowie (pokrywa)",pc:"podkorowy ośrodek wzroku (odruchy wzrokowe)"},
{p:"I",t:"wzgórki dolne pokrywy",co:"część blaszki czworaczej",gd:"śródmózgowie (pokrywa)",pc:"podkorowy ośrodek słuchu (odruchy słuchowe)"},
{p:"I",t:"wzgórze",l:"thalamus",co:"skupisko jąder istoty szarej",gd:"ściany boczne komory III",pc:"główna stacja przekaźnikowa czucia do kory"},
{p:"I",t:"wyniosłość piramidowa",l:"eminentia pyramidalis",co:"podłużna wyniosłość na powierzchni mostu",gd:"przednia (podstawna) powierzchnia mostu, po bokach bruzdy podstawnej",zc:"włókna piramidowe (korowo-rdzeniowe) biegnące w moście",pc:"powierzchowny ślad drogi piramidowej w moście"},
{p:"I",t:"wyspa",l:"insula",co:"kora ukryta w głębi",gd:"w bruździe bocznej (Sylwiusza), pod wieczkami",pc:"smak, czucie trzewne, emocje"},
{p:"I",t:"zgrubienie lędźwiowe",l:"intumescentia lumbosacralis",co:"poszerzenie rdzenia",gd:"odcinek lędźwiowo-krzyżowy",pc:"zaopatruje kończynę dolną"},
{p:"I",t:"zgrubienie szyjne",l:"intumescentia cervicalis",co:"poszerzenie rdzenia",gd:"C4–Th1",pc:"zaopatruje kończynę górną (splot ramienny)"},
{p:"I",t:"zwój rdzeniowy",l:"ganglion spinale",co:"skupisko ciał neuronów czuciowych",gd:"na korzeniu tylnym",zc:"neurony pozornie jednobiegunowe",pc:"I neuron drogi czuciowej"},
{p:"I",t:"zakręt zaśrodkowy",l:"gyrus postcentralis",co:"zakręt płata ciemieniowego",gd:"za bruzdą środkową",pc:"kora czuciowa"},
{p:"I",t:"zakręt przedśrodkowy",l:"gyrus precentralis",co:"zakręt płata czołowego",gd:"przed bruzdą środkową",pc:"kora ruchowa"},
{p:"I",t:"zakręty oczodołowe",co:"zakręty dolnej powierzchni płata czołowego",gd:"powierzchnia oczodołowa",pc:"węch, układ limbiczny, kontrola zachowania"},
{p:"I",t:"zakręty skroniowe",co:"zakręty płata skroniowego",gd:"górny, środkowy, dolny",pc:"słuch; rozumienie mowy (Wernicke w górnym)"},
{p:"I",t:"zakręt hipokampa",l:"gyrus parahippocampalis",co:"kora przyśrodkowej powierzchni płata skroniowego",gd:"obok hipokampa",pc:"układ limbiczny (pamięć, węch)"},
{p:"I",t:"bruzda ostrogowa",l:"sulcus calcarinus",co:"bruzda płata potylicznego",gd:"powierzchnia przyśrodkowa",pc:"wokół niej leży kora wzrokowa"},
{p:"I",t:"pień współczulny",l:"truncus sympathicus",co:"łańcuch zwojów przykręgowych",gd:"po obu stronach kręgosłupa",pc:"przełączanie włókien współczulnych"},
{p:"I",t:"zwój trzewny",l:"ganglion coeliacum",co:"zwój przedkręgowy współczulny",gd:"jama brzuszna (przy pniu trzewnym)",pc:"żołądek, wątroba, trzustka, śledziona"},
{p:"I",t:"zwój krezkowy górny",co:"zwój przedkręgowy współczulny",gd:"jama brzuszna",pc:"jelito cienkie i prawa część okrężnicy"},
{p:"I",t:"zwój krezkowy dolny",co:"zwój przedkręgowy współczulny",gd:"jama brzuszna",pc:"lewa część okrężnicy i narządy miednicy"},
// ===== CZĘŚĆ II — PODSTAWOWE POJĘCIA NEUROANATOMICZNE I NEUROFIZJOLOGICZNE =====
{p:"II",t:"bodziec",co:"zmiana w środowisku zdolna pobudzić receptor",pc:"wywołuje impuls"},
{p:"II",t:"czucie",co:"odbiór bodźców — świadomy lub nieuświadomiony"},
{p:"II",t:"czucie protopatyczne",co:"czucie grube: ból, temperatura, dotyk gruby",pc:"droga rdzeniowo-wzgórzowa"},
{p:"II",t:"czucie epikrytyczne",co:"czucie dokładne, różnicujące (lokalizacja, dyskryminacja)",pc:"sznury tylne → wstęga przyśrodkowa"},
{p:"II",t:"czucie głębokie",co:"czucie z mięśni, ścięgien i stawów (= proprioceptywne)",pc:"świadome (sznury tylne) i nieświadome (drogi móżdżkowe)"},
{p:"II",t:"czucie proprioceptywne",co:"czucie położenia i ruchu ciała (głębokie)"},
{p:"II",t:"czucie wisceralne",co:"czucie z narządów wewnętrznych",pc:"przewodzone włóknami autonomicznymi"},
{p:"II",t:"dendryt",co:"krótka, rozgałęziona wypustka neuronu",pc:"odbiera impulsy i przewodzi do perikarionu"},
{p:"II",t:"dermatom",co:"pas skóry",gd:"unerwiony czuciowo przez jeden neuromer"},
{p:"II",t:"droga aferentna",co:"droga dośrodkowa (czuciowa) — z receptorów do ośrodków"},
{p:"II",t:"droga eferentna",co:"droga odśrodkowa (ruchowa) — do efektorów"},
{p:"II",t:"droga kojarzeniowa (asocjacyjna)",co:"łączy okolice kory tej samej półkuli"},
{p:"II",t:"droga nerwowa",l:"tractus",co:"pęczek włókien o wspólnym przebiegu i czynności"},
{p:"II",t:"droga rzutowa (projekcyjna)",co:"łączy korę z niższymi piętrami (w górę lub w dół)"},
{p:"II",t:"droga spoidłowa (komisuralna)",co:"łączy okolice obu półkul (przez spoidła)"},
{p:"II",t:"efektor",co:"narząd wykonawczy: mięsień lub gruczoł",pc:"koniec drogi ruchowej"},
{p:"II",t:"glej (neuroglej)",l:"glia",co:"komórki podporowe układu nerwowego",pc:"odżywianie, izolacja, mielina, obrona"},
{p:"II",t:"impuls",co:"fala pobudzenia (potencjał czynnościowy) wzdłuż włókna"},
{p:"II",t:"istota biała",co:"skupiska włókien (aksonów z mieliną)",pc:"tworzy drogi"},
{p:"II",t:"istota szara",co:"skupiska perikarionów (ciał komórek)",pc:"kora i jądra"},
{p:"II",t:"jądro nerwowe",l:"nucleus",co:"skupisko perikarionów o wspólnej czynności w OUN"},
{p:"II",t:"jądro ruchowe",co:"jądro zawierające ciała neuronów ruchowych"},
{p:"II",t:"jądro początkowe",co:"jądro, w którym zaczyna się droga lub nerw"},
{p:"II",t:"jądro końcowe",co:"jądro, w którym kończy się droga lub nerw"},
{p:"II",t:"jądro czuciowe",co:"jądro odbierające włókna czuciowe"},
{p:"II",t:"jądro autonomiczne",co:"jądro układu wegetatywnego (współczulne lub przywspółczulne)"},
{p:"II",t:"jądro współczulne",co:"jądro autonomiczne sympatyczne (np. pośrednio-boczne)"},
{p:"II",t:"jądro przywspółczulne",co:"jądro autonomiczne parasympatyczne (np. krzyżowe, ślinowe)"},
{p:"II",t:"jądro sympatyczne",co:"= jądro współczulne"},
{p:"II",t:"jądro parasympatyczne",co:"= jądro przywspółczulne"},
{p:"II",t:"łuk odruchowy",co:"droga odruchu: receptor → neuron czuciowy → ośrodek → neuron ruchowy → efektor"},
{p:"II",t:"neurofibryle",co:"włókienka cytoszkieletu w cytoplazmie neuronu",pc:"rola podporowa i transportowa"},
{p:"II",t:"neuromer",co:"segment rdzenia odpowiadający jednej parze nerwów rdzeniowych (31)"},
{p:"II",t:"neuron",l:"neuronum",co:"podstawowa, pobudliwa komórka nerwowa",pc:"przewodzi impulsy"},
{p:"II",t:"neuron pozornie jednobiegunowy",co:"neuron czuciowy zwoju z jedną wypustką dzielącą się w kształt T"},
{p:"II",t:"neuron przedzwojowy",co:"autonomiczny: ciało w OUN, akson do zwoju"},
{p:"II",t:"neuron zazwojowy",co:"autonomiczny: ciało w zwoju, akson do narządu"},
{p:"II",t:"neurosekrecja",co:"wydzielanie hormonów przez wyspecjalizowane neurony"},
{p:"II",t:"neurotransmiter",co:"substancja chemiczna przenosząca sygnał w synapsie"},
{p:"II",t:"neuryt (akson)",l:"axon",co:"pojedyncza, długa wypustka neuronu",pc:"przewodzi impuls od perikarionu"},
{p:"II",t:"odruch",co:"automatyczna odpowiedź efektora na bodziec, bez udziału woli"},
{p:"II",t:"opona",l:"meninx",co:"błona okrywająca OUN (twarda, pajęcza, miękka)",pc:"ochrona i podtrzymywanie"},
{p:"II",t:"osłonka mielinowa (rdzenna)",co:"lipidowa osłonka aksonu",pc:"izolacja i szybsze, skokowe przewodzenie"},
{p:"II",t:"ośrodek nerwowy",co:"czynnościowe skupisko neuronów odpowiadające za daną funkcję"},
{p:"II",t:"perikarion (neurocyt)",co:"ciało komórki nerwowej (z jądrem i organellami)"},
{p:"II",t:"pęcherzyk mózgowy pierwotny",co:"jeden z 3 wczesnych pęcherzyków cewy: przodo-, śród-, tyłomózgowie"},
{p:"II",t:"pęcherzyk mózgowy wtórny",co:"jeden z 5: kreso-, między-, śródmózgowie, tyłomózgowie wtórne, rdzeniomózgowie"},
{p:"II",t:"receptor",co:"struktura odbierająca bodziec i zamieniająca go na impuls",pc:"początek drogi czuciowej"},
{p:"II",t:"splot naczyniówkowy",l:"plexus choroideus",co:"unaczyniona tkanka w komorach",pc:"wytwarza płyn mózgowo-rdzeniowy"},
{p:"II",t:"splot nerwowy",l:"plexus",co:"sieć łączących się gałęzi nerwów wymieniających włókna"},
{p:"II",t:"spoidło",l:"commissura",co:"pasmo włókien łączące symetryczne części obu połów mózgu"},
{p:"II",t:"sterowanie",co:"nadrzędna regulacja czynności narządów (pojęcie cybernetyczne)",pc:"realizowane przez układ nerwowy i hormonalny ze sprzężeniami zwrotnymi"},
{p:"II",t:"stożek rdzeniowy",l:"conus medullaris",co:"stożkowate zakończenie rdzenia",gd:"wysokość L1–L2"},
{p:"II",t:"synapsa",co:"miejsce kontaktu przekazujące impuls między neuronami (zwykle chemicznie)"},
{p:"II",t:"torebki mózgowe",co:"historyczne określenie błon/otoczek pierwotnych pęcherzyków mózgowia",pc:"(termin rzadki — warto zweryfikować z wykładem)"},
{p:"II",t:"nić końcowa",l:"filum terminale",co:"pasmo (głównie opony miękkiej) od stożka do kości guzicznej",pc:"mocuje rdzeń"},
{p:"II",t:"włókno dośrodkowe",co:"włókno czuciowe — biegnące do OUN"},
{p:"II",t:"włókno obwodowe",co:"włókno biegnące w nerwie na obwód (do efektora lub od receptora)"},
{p:"II",t:"neuron ośrodkowy",co:"neuron leżący w OUN"},
{p:"II",t:"neuron obwodowy",co:"neuron, którego ciało lub wypustka leży poza OUN"},
{p:"II",t:"zakręt mózgowy",l:"gyrus",co:"fałd kory mózgu (między bruzdami)"},
{p:"II",t:"zwój nerwowy",l:"ganglion",co:"skupisko perikarionów poza OUN (czuciowy lub autonomiczny)"},
// ===== CZĘŚĆ III/IV — PRZESYŁANIE IMPULSÓW I TEMATY RÓŻNE =====
{p:"III/IV",t:"3 neurony czucia (protopatyczne, epikrytyczne, proprioceptywne)",co:"schemat 3-neuronowy drogi czuciowej",gd:"I neuron w zwoju, II w rdzeniu/pniu (tu krzyżowanie), III we wzgórzu",pc:"przewodzenie czucia z receptorów do kory czuciowej"},
{p:"III/IV",t:"drogi domóżdżkowe",co:"drogi rdzeniowo-móżdżkowe (przednia Gowersa, tylna Flechsiga)",pc:"czucie głębokie nieświadome do móżdżku (koordynacja ruchu)"},
{p:"III/IV",t:"drogi piramidowe (oba neurony główne)",co:"korowo-rdzeniowe (boczna i przednia) + korowo-jądrowa",zc:"neuron ośrodkowy (kora ruchowa) + obwodowy (róg przedni / jądro ruchowe nn.)",pc:"ruchy dowolne mięśni głowy, szyi, tułowia i kończyn"},
{p:"III/IV",t:"ośrodki i drogi pozapiramidowe",co:"ośrodki: prążkowie, gałka blada, istota czarna, jądro czerwienne, twór siatkowaty",zc:"drogi: czerwienno-, przedsionkowo-, siatkowo-, pokrywowo-, oliwkowo-rdzeniowa",pc:"napięcie mięśni, postawa, ruchy automatyczne"},
{p:"III/IV",t:"płyn mózgowo-rdzeniowy — powstawanie i drogi odpływu",co:"powstaje w splotach naczyniówkowych komór",pc:"komory boczne → III → wodociąg → IV → otwory Magendiego/Luschki → przestrzeń podpajęczynówkowa → ziarnistości pajęczynówki → zatoki żylne"},
{p:"III/IV",t:"opony mózgowe i rdzeniowe",co:"twarda, pajęcza, miękka; między pajęczą a miękką płyn m-r",pc:"ochrona, podtrzymanie i krążenie płynu"},
{p:"III/IV",t:"układ limbiczny",co:"zespół struktur przyśrodkowej powierzchni półkul",pc:"emocje, pamięć i popędy (krąg Papeza)"},
{p:"III/IV",t:"twór siatkowaty",co:"sieć neuronów w nakrywce pnia",pc:"czuwanie (ARAS), ośrodki życiowe, napięcie mięśni"},
{p:"III/IV",t:"unerwienie mięśni i okolic skóry (nerwy i poziomy neuromerów)",co:"każdy mięsień i dermatom ma swój nerw i poziom rdzeniowy",pc:"np. przepona — nerw przeponowy (C3–C5); dermatomy ułożone segmentowo"},
];

